### ISSUE TITLE
ReferenceError: through is not defined

### ISSUE THREAD

**Issue by aijanai** [pelger/docker-stats#11]
Hi,

the package doesn't work. It complains about missing through:

ai_ja_nai@aiMacBookPro:~/loadtest$ node docker-stats.js 
/home/ai_ja_nai/loadtest/docker-stats.js:13
stats(opts).pipe(through.obj(function(chunk, enc, cb) {
                 ^

ReferenceError: through is not defined
    at Object.<anonymous> (/home/ai_ja_nai/loadtest/docker-stats.js:13:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

I installed through and through2, but didn't help.

**Comment by mcollina** [comment]
which version of Node.js are you using? How did you installed docker-stats?

**Comment by aijanai** [comment]
6.9.2, npm i

**Comment by mcollina** [comment]
This seems strange, you are running `node docker-stats.js`, while this project just offer a `stats.js` file. Assuming you have written that, you need to do a `var through = require('through2')` somewhere before line 13.

**Comment by aijanai** [comment]
I just copied and paste what I've seen here: https://www.npmjs.com/package/docker-stats

Maybe the page should be fixed

**Comment by mcollina** [comment]
@aijanai it has been already fixed, thanks for reporting.
