### ISSUE TITLE
Not working out of the box

### ISSUE THREAD

**Issue by jeffutter** [pelger/docker-stats#16]
I tried checking out this project using the example provided in the readme. I run into this issue right off the bad. Any suggestions what might be going on here?

I'm using the latest docker-for-mac if that makes a difference.

```
>>> node index.js
/myapp/node_modules/docker-stats/stats.js:92
    ).pipe(result, { end: false })
     ^

TypeError: Cannot read property 'pipe' of undefined
    at EventEmitter.attachContainer (/myapp/node_modules/docker-stats/stats.js:92:6)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at emit (/myapp/node_modules/docker-allcontainers/allcontainers.js:155:12)
    at Array.forEach (<anonymous>)
    at Object.callback (/myapp/node_modules/docker-allcontainers/allcontainers.js:127:24)
    at /myapp/node_modules/dockerode/lib/docker.js:433:12
    at Modem.buildPayload (/myapp/node_modules/docker-modem/lib/modem.js:270:7)
    at IncomingMessage.<anonymous> (/myapp/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:110:20)```

**Comment by megastef** [comment]
+1 - I just upgraded to latest docker stats and got the same error

**Comment by megastef** [comment]
@mcollina I think the pump package needs an update to 3.0.0 to solve this issue

**Comment by megastef** [comment]
It seems the version published on npm 0.8.0 does not match the source code in this repository. See package.json version number

**Comment by mcollina** [comment]
just pushed, sorry


Il giorno ven 13 apr 2018 alle ore 00:03 Stefan Thies <
notifications@github.com> ha scritto:

**Comment by aRobinson-R7** [comment]
+1 Still having this issue with v0.8.0
