### ISSUE TITLE
Error when used in a docker container

### ISSUE THREAD

**Issue by marcwaz** [pelger/docker-stats#17]
I have retrieved your files in a directory called test.
then: 
docker build -t test/test:latest ./test
then:
docker run --name test -v /var/run/docker.sock:/var/run/docker.sock:ro -d test/test:latest

The result of : docker logs test

> docker-stats@0.8.0 start /usr/src/app
> ./stats.js

/usr/src/app/stats.js:92
    ).pipe(result, { end: false })
     ^

TypeError: Cannot read property 'pipe' of undefined
    at EventEmitter.attachContainer (/usr/src/app/stats.js:92:6)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at emit (/usr/src/app/node_modules/docker-allcontainers/allcontainers.js:155:12)
    at Array.forEach (native)
    at Object.callback (/usr/src/app/node_modules/docker-allcontainers/allcontainers.js:127:24)
    at /usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/lib/docker.js:429:12
    at Modem.buildPayload (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:270:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:72:20)

npm ERR! Linux 4.4.0-134-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
npm ERR! docker-stats@0.8.0 start: `./stats.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docker-stats@0.8.0 start script './stats.js'.
npm ERR! This is most likely a problem with the docker-stats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./stats.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs docker-stats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls docker-stats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

This command returns : docker version

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by marcwaz** [comment]
The fork of rubenhak/docker-stats fix this issue. thx
